periodics:
- name: ci-structured-merge-diff-test
  interval: 12h
  labels:
    preset-service-account: "true"
  decorate: true
  extra_refs:
  - org: kubernetes-sigs
    repo: structured-merge-diff
    base_ref: master
    path_alias: sigs.k8s.io/structured-merge-diff
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-master
      command:
      - go
      args:
      - test
      - ./...
- name: ci-structured-merge-diff-gofmt
  interval: 12h
  labels:
    preset-service-account: "true"
  decorate: true
  extra_refs:
  - org: kubernetes-sigs
    repo: structured-merge-diff
    base_ref: master
    path_alias: sigs.k8s.io/structured-merge-diff
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-master
      command:
      - bash
      - -c
      - test -z "$({ find . -name "*.go" | grep -v "\\/vendor\\/" | xargs gofmt -s -d | tee /dev/stderr; })"
