presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-cross
    run_if_changed: '^((build\/|hack\/lib\/).*)|(.*Makefile.*)$'
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/bootstrap:v20190213-2f4f06285
        args:
        - "--job=$(JOB_NAME)"
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--service-account=/etc/service-account/service-account.json"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--timeout=90"
        - --scenario=execute
        - --
        - --env=KUBE_RELEASE_RUN_TESTS=n
        - make
        - release
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 7
            memory: "41Gi"

periodics:
- interval: 5m
  name: ci-kubernetes-build-fast
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/bootstrap:v20190213-2f4f06285
      args:
      - --repo=k8s.io/kubernetes
      - --repo=k8s.io/release
      - --root=/go/src
      - --timeout=30
      - --scenario=kubernetes_build
      - --
      - --allow-dup
      - --fast
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 4
          memory: "8Gi"

- interval: 4h
  name: ci-kubernetes-build-debian-unstable
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/bootstrap:v20190213-2f4f06285
      args:
      - --repo=k8s.io/release
      - --root=/go/src
      - --timeout=180
      - --scenario=execute
      - --
      - ./debian/jenkins.sh
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 4
          memory: "8Gi"
- interval: 1h
  name: ci-kubernetes-build
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  annotations:
    fork-per-release: "true"
    fork-per-release-replacements: "--extra-publish-file=k8s-master -> --extra-publish-file=k8s-{{.Version}}"
    testgrid-dashboards: sig-release-master-informing
  spec:
    containers:
      - image: gcr.io/k8s-testimages/bootstrap:v20190213-2f4f06285
        args:
          - --repo=k8s.io/kubernetes=release
          - --repo=k8s.io/release
          - --root=/go/src
          - --timeout=180
          - --scenario=kubernetes_build
          - --
          - --allow-dup
          - --extra-publish-file=k8s-master
          - --hyperkube
          - --registry=gcr.io/kubernetes-ci-images
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 4
            memory: "8Gi"
- interval: 1h
  name: ci-kubernetes-cross-build
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/bootstrap:v20190213-2f4f06285
      args:
      - --repo=k8s.io/kubernetes
      - --repo=k8s.io/release
      - --root=/go/src
      - --timeout=120
      - --scenario=kubernetes_build
      - --
      - --hyperkube
      - --registry=gcr.io/kubernetes-ci-images
      - --suffix=-cross
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 7
          memory: "41Gi"
