presets:
- labels:
    preset-ci-gce-device-plugin-gpu: "true"
  env:
  - name: KUBE_GCE_NODE_IMAGE
    value: gke-1134-gke-rc5-cos-69-10895-138-0-v190320-pre-nvda-gpu
  - name: KUBE_GCE_NODE_PROJECT
    value: gke-node-images
  - name: NODE_ACCELERATORS
    value: type=nvidia-tesla-k80,count=2

periodics:
- name: ci-kubernetes-e2e-gce-device-plugin-gpu
  cron: "30 1-23/2 * * *"
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-ci-gce-device-plugin-gpu: "true"
  spec:
    containers:
    - args:
      - --timeout=300
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --extract=ci/latest
      - --gcp-node-image=gci
      - --gcp-project-type=gpu-project
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:GPUDevicePlugin\] --minStartupPods=8
      - --timeout=180m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-master

- name: ci-kubernetes-e2e-gce-device-plugin-gpu-beta
  cron: "0 0-23/2 * * *"
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-ci-gce-device-plugin-gpu: "true"
  spec:
    containers:
    - args:
      - --timeout=300
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --extract=ci/k8s-beta
      - --gcp-node-image=gci
      - --gcp-project-type=gpu-project
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:GPUDevicePlugin\] --minStartupPods=8
      - --timeout=180m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-master

- name: ci-kubernetes-e2e-gce-device-plugin-gpu-stable1
  cron: "0 3-23/6 * * *"
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-ci-gce-device-plugin-gpu: "true"
  spec:
    containers:
    - args:
      - --timeout=300
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --extract=ci/k8s-stable1
      - --gcp-project-type=gpu-project
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:GPUDevicePlugin\] --minStartupPods=8
      - --timeout=180m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-master

- name: ci-kubernetes-e2e-gce-device-plugin-gpu-stable2
  cron: "0 8-23/12 * * *"
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-ci-gce-device-plugin-gpu: "true"
  spec:
    containers:
    - args:
      - --timeout=300
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --extract=ci/k8s-stable2
      - --gcp-project-type=gpu-project
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:GPUDevicePlugin\] --minStartupPods=8
      - --timeout=180m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-master
