periodics:
- name: periodic-cluster-api-provider-aws-test-creds
  decorate: true
  interval: 4h
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-aws
    base_ref: master
    path_alias: "sigs.k8s.io/cluster-api-provider-aws"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-1.14
      command:
      - "./scripts/ci-aws-cred-test.sh"
- name: periodic-cluster-api-provider-aws-bazel-e2e
  decorate: true
  interval: 1h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-aws
    base_ref: master
    path_alias: "sigs.k8s.io/cluster-api-provider-aws"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-1.14
      command: ["runner.sh"]
      args: ["make", "e2e"]
      env:
      - name: BOSKOS_HOST
        value: "boskos.test-pods.svc.cluster.local"
      - name: AWS_REGION
        value: "us-west-2"
      securityContext:
        privileged: true
postsubmits:
  kubernetes-sigs/cluster-api-provider-aws:
  - name: ci-cluster-api-provider-aws-bazel-e2e
    path_alias: "sigs.k8s.io/cluster-api-provider-aws"
    decorate: true
    max_concurrency: 5
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
      preset-service-account: "true"
      preset-aws-ssh: "true"
      preset-aws-credential: "true"
    branches:
    - ^master$
    - ^release-.*$
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-1.14
        command: ["runner.sh"]
        args: ["make", "e2e"]
        env:
        - name: BOSKOS_HOST
          value: "boskos.test-pods.svc.cluster.local"
        - name: AWS_REGION
          value: "us-west-2"
        securityContext:
          privileged: true
