presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-e2e-gce-storage-slow
    always_run: false
    optional: true
    # All the files owned by sig-storage. Keep in sync across
    # all sig-storage-jobs
    #
    # pkg/controller/volume
    # pkg/kubelet/volumemanager
    # pkg/volume
    # pkg/util/mount
    # test/e2e/storage
    # test/e2e/testing-manifests/storage-csi
    run_if_changed: '^(pkg\/controller\/volume|pkg\/kubelet\/volumemanager|pkg\/volume|pkg\/util\/mount|test\/e2e\/storage|test\/e2e\/testing-manifests\/storage-csi)'
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
      preset-pull-kubernetes-e2e: "true"
      preset-pull-kubernetes-e2e-gce: "true"
    spec:
      containers:
      - args:
        - --root=/go/src
        - --repo=k8s.io/kubernetes=$(PULL_REFS)
        - --repo=k8s.io/release
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --timeout=125
        - --scenario=kubernetes_e2e
        - --
        - --build=bazel
        - --cluster=
        - --extract=local
        - --gcp-node-image=gci
        - --gcp-zone=us-west1-b
        - --ginkgo-parallel=30
        - --provider=gce
        - --runtime-config=batch/v2alpha1=true
        - --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce-storage-slow
        - --test_args=--ginkgo.focus=\[sig-storage\].*\[Slow\] --ginkgo.skip=\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|gcePD-external --minStartupPods=8
        - --timeout=80m
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-master
        resources:
          requests:
            memory: "6Gi"
  - name: pull-kubernetes-e2e-gce-csi-serial
    always_run: false
    optional: true
    # All the files owned by sig-storage. Keep in sync across
    # all sig-storage-jobs
    #
    # pkg/controller/volume
    # pkg/kubelet/volumemanager
    # pkg/volume
    # pkg/util/mount
    # test/e2e/storage
    # test/e2e/testing-manifests/storage-csi
    run_if_changed: '^(pkg\/controller\/volume|pkg\/kubelet\/volumemanager|pkg\/volume|pkg\/util\/mount|test\/e2e\/storage|test\/e2e\/testing-manifests\/storage-csi)'
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
      preset-pull-kubernetes-e2e: "true"
      preset-pull-kubernetes-e2e-gce: "true"
    spec:
      containers:
      - args:
        - --root=/go/src
        - --repo=k8s.io/kubernetes=$(PULL_REFS)
        - --repo=k8s.io/release
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --timeout=150
        - --scenario=kubernetes_e2e
        - --
        - --build=bazel
        - --cluster=
        - --extract=local
        - --gcp-node-image=gci
        - --gcp-zone=us-west1-b
        - --provider=gce
        - --runtime-config=batch/v2alpha1=true
        - --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce-csi-serial
        - --test_args=--ginkgo.focus=CSI.*(\[Serial\]|\[Disruptive\]) --ginkgo.skip=\[Flaky\]|\[Feature:.+\]|gcePD-external --minStartupPods=8
        - --timeout=120m
        image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-master
        resources:
          requests:
            memory: "6Gi"
