periodics:
- interval: 6h
  name: ci-kubernetes-gce-conformance-latest
  annotations:
    fork-per-release: "true"
    fork-per-release-replacements: "--extract=ci/latest -> --extract=ci/latest-{{.Version}}"
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=220
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --extract=ci/latest
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Conformance\] --ginkgo.skip=Alpha|\[(Disruptive|Feature:[^\]]+|Flaky)\]
      - --timeout=200m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-master

# manual-release-bump-required (add a job for the new version and delete the job for the oldest version)
- interval: 6h
  name: ci-kubernetes-gce-conformance-stable-1-11
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=220
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --extract=release/stable-1.11
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Conformance\] --ginkgo.skip=Alpha|Kubectl|\[(Disruptive|Feature:[^\]]+|Flaky)\]
      - --timeout=200m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-1.11

- interval: 6h
  name: ci-kubernetes-gce-conformance-stable-1-12
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=220
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --extract=release/stable-1.12
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Conformance\] --ginkgo.skip=Alpha|\[(Disruptive|Feature:[^\]]+|Flaky)\]
      - --timeout=200m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-1.12

- interval: 6h
  name: ci-kubernetes-gce-conformance-stable-1-13
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=220
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --extract=release/stable-1.13
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Conformance\] --ginkgo.skip=Alpha|\[(Disruptive|Feature:[^\]]+|Flaky)\]
      - --timeout=200m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-1.13

- interval: 6h
  name: ci-kubernetes-gce-conformance-stable-1-14
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=220
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --extract=release/stable-1.14
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Conformance\] --ginkgo.skip=Alpha|\[(Disruptive|Feature:[^\]]+|Flaky)\]
      - --timeout=200m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-1.14
