presets:
- labels:
    preset-e2e-gce-windows: "true"
  env:
  - name: KUBE_GCE_ENABLE_IP_ALIASES
    value: "true"
  - name: NUM_WINDOWS_NODES
    value: "3"
  - name: NUM_NODES
    value: "2"
  - name: KUBERNETES_NODE_PLATFORM
    value: "windows"

periodics:
- name: ci-kubernetes-e2e-windows-gce-poc
  decorate: true
  extra_refs:
  - org: pjh
    repo: kubernetes
    base_ref: windows-gce-poc
    path_alias: k8s.io/kubernetes
  - org: yujuhong
    repo: gce-k8s-windows-testing
    base_ref: master
    path_alias: k8s.io/gce-k8s-windows-testing
  - org: kubernetes
    repo: release
    base_ref: master
    path_alias: k8s.io/release
  interval: 2h
  labels:
    preset-k8s-ssh: "true"
    preset-e2e-gce-windows: "true"
    preset-service-account: "true"
    preset-bazel-scratch-dir: "true"
    preset-bazel-remote-cache-enabled: "true"
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --check-leaked-resources
      - --cluster=
      - --build=bazel
      - --stage=gs://kubernetes-release-dev/ci/ci-kubernetes-e2e-windows-gce-poc
      - --extract=local
      - --gcp-zone=us-west1-b
      - --ginkgo-parallel=8
      - --provider=gce
      - --gcp-nodes=2
      - --test=false
      - --test-cmd=$GOPATH/src/k8s.io/gce-k8s-windows-testing/run-e2e.sh
      - --test-cmd-args=--ginkgo.focus=\[Conformance\]|\[NodeConformance\]|\[sig-windows\] --ginkgo.skip=\[LinuxOnly\]|\[Serial\]|\[Feature:.+\] --minStartupPods=8
      - --test-cmd-args=--node-os-distro=windows
      - --timeout=120m
      env:
      - name: OVERRIDE_NODE_BINARY_TAR_URL
        value: "https://storage.googleapis.com/kubernetes-release/release/v1.14.1/kubernetes-node-windows-amd64.tar.gz"
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-master
      resources:
        requests:
          memory: "8Gi"

- name: ci-kubernetes-e2e-windows-gce
  decorate: true
  extra_refs:
  - org: yujuhong
    repo: gce-k8s-windows-testing
    base_ref: master
    path_alias: k8s.io/gce-k8s-windows-testing
  interval: 2h
  labels:
    preset-k8s-ssh: "true"
    preset-service-account: "true"
    preset-e2e-gce-windows: "true"
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --check-leaked-resources
      - --cluster=
      - --extract=ci-cross/latest
      - --gcp-zone=us-west1-b
      - --ginkgo-parallel=8
      - --provider=gce
      - --gcp-nodes=2
      - --test=false
      - --test-cmd=$GOPATH/src/k8s.io/gce-k8s-windows-testing/run-e2e.sh
      - --test-cmd-args=--ginkgo.focus=\[Conformance\]|\[NodeConformance\]|\[sig-windows\] --ginkgo.skip=\[LinuxOnly\]|\[Serial\]|\[Feature:.+\] --minStartupPods=8
      - --test-cmd-args=--node-os-distro=windows
      - --timeout=120m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-master

- name: ci-kubernetes-e2e-windows-gce-k8sbeta
  decorate: true
  extra_refs:
  - org: yujuhong
    repo: gce-k8s-windows-testing
    base_ref: master
    path_alias: k8s.io/gce-k8s-windows-testing
  interval: 2h
  labels:
    preset-k8s-ssh: "true"
    preset-service-account: "true"
    preset-e2e-gce-windows: "true"
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --check-leaked-resources
      - --cluster=
      - --extract=ci/k8s-beta
      - --gcp-zone=us-west1-b
      - --ginkgo-parallel=8
      - --provider=gce
      - --gcp-nodes=2
      - --test=false
      - --test-cmd=$GOPATH/src/k8s.io/gce-k8s-windows-testing/run-e2e.sh
      - --test-cmd-args=--ginkgo.focus=\[Conformance\]|\[NodeConformance\]|\[sig-windows\] --ginkgo.skip=\[LinuxOnly\]|\[Serial\]|\[Feature:.+\] --minStartupPods=8
      - --test-cmd-args=--node-os-distro=windows
      - --timeout=120m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-master

- name: ci-kubernetes-e2e-windows-gce-alpha-features
  decorate: true
  extra_refs:
  - org: yujuhong
    repo: gce-k8s-windows-testing
    base_ref: master
    path_alias: k8s.io/gce-k8s-windows-testing
  interval: 2h
  labels:
    preset-k8s-ssh: "true"
    preset-service-account: "true"
    preset-e2e-gce-windows: "true"
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --check-leaked-resources
      - --cluster=
      - --extract=ci-cross/latest
      - --gcp-zone=us-west1-b
      - --ginkgo-parallel=8
      - --provider=gce
      - --gcp-nodes=2
      - --test=false
      - --test-cmd=$GOPATH/src/k8s.io/gce-k8s-windows-testing/run-e2e.sh
      - --test-cmd-args=--ginkgo.focus=\[Conformance\]|\[NodeConformance\]|\[sig-windows\] --ginkgo.skip=\[LinuxOnly\]|\[Serial\] --minStartupPods=8
      - --test-cmd-args=--node-os-distro=windows
      - --timeout=120m
      env:
      - name: KUBE_FEATURE_GATES
        value: "WindowsGMSA=true"
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-master

- name: ci-kubernetes-e2e-windows-gce-serial
  decorate: true
  extra_refs:
  - org: yujuhong
    repo: gce-k8s-windows-testing
    base_ref: master
    path_alias: k8s.io/gce-k8s-windows-testing
  interval: 4h
  labels:
    preset-k8s-ssh: "true"
    preset-service-account: "true"
    preset-e2e-gce-windows: "true"
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --check-leaked-resources
      - --cluster=
      - --extract=ci-cross/latest
      - --gcp-zone=us-west1-b
      - --ginkgo-parallel=1
      - --provider=gce
      - --gcp-nodes=2
      - --test=false
      - --test-cmd=$GOPATH/src/k8s.io/gce-k8s-windows-testing/run-e2e.sh
      - --test-cmd-args=--ginkgo.focus=\[Conformance\]|\[NodeConformance\]|\[sig-windows\]|\[Feature:Windows\] --ginkgo.skip=\[Flaky\]|\[LinuxOnly\] --minStartupPods=8
      - --test-cmd-args=--node-os-distro=windows
      - --timeout=240m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-master

presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-e2e-windows-gce
    decorate: true
    path_alias: k8s.io/kubernetes
    extra_refs:
    - org: yujuhong
      repo: gce-k8s-windows-testing
      base_ref: master
      path_alias: k8s.io/gce-k8s-windows-testing
    labels:
      preset-k8s-ssh: "true"
      preset-service-account: "true"
      preset-e2e-gce-windows: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
    always_run: false
    optional: true
    branches:
    - master
    spec:
      containers:
      - command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
        - --build=gce-windows-bazel
        - --check-leaked-resources
        - --cluster=
        - --extract=local
        - --gcp-zone=us-west1-b
        - --ginkgo-parallel=8
        - --provider=gce
        - --gcp-nodes=2
        - --test=false
        - --test-cmd=$GOPATH/src/k8s.io/gce-k8s-windows-testing/run-e2e.sh
        - --test-cmd-args=--ginkgo.focus=\[Conformance\]|\[NodeConformance\]|\[sig-windows\] --ginkgo.skip=\[LinuxOnly\]|\[Serial\]|\[Feature:.+\] --minStartupPods=8
        - --test-cmd-args=--node-os-distro=windows
        - --timeout=120m
        image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-master
        resources:
          requests:
            memory: "6Gi"
