presubmits:
  kubernetes/test-infra:
  - name: pull-test-infra-build-smoke
    agent: knative-build
    decorate: true
    build_spec:
      steps:
      - name: first
        image: busybox
        args: ["echo", "hello"]
      - name: second
        image: busybox
        args: ["echo", "world"]
      - name: third
        image: busybox
        args: ["cat", "config/jobs/kubernetes/test-infra/test-infra-presubmits.yaml"]
  - name: pull-test-infra-build-smoke-fail
    agent: knative-build
    decorate: true
    build_spec:
      steps:
      - name: first
        image: busybox
        args: ["echo", "hello"]
      - name: second
        image: busybox
        args: ["sleep", "60"]
      - name: third
        image: busybox
        args: ["exit", "1"]

  - name: pull-test-infra-bazel
    branches:
    - master
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: launcher.gcr.io/google/bazel:0.24.1
        command:
        - hack/bazel.sh
        args:
        - test
        - --config=ci
        - --config=unit
        - --nobuild_tests_only
        - //...

  - name: pull-test-infra-gubernator
    branches:
    - master
    run_if_changed: 'gubernator|prow/config.yaml'
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/gubernator:0.4
        command:
        - ./gubernator/test-gubernator.sh
        env:
        - name: WORKSPACE
          value: "/workspace"

  - name: pull-test-infra-lint
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: launcher.gcr.io/google/bazel:0.24.1
        command:
        - hack/bazel.sh
        args:
        - test
        - --config=ci
        - --config=lint
        - //...

  - name: pull-test-infra-verify-tslint
    branches:
      - master
    run_if_changed: '\.ts$'
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
        - image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-experimental
          command:
            - ./hack/verify-tslint.sh

  - name: pull-test-infra-verify-bazel
    branches:
    - master
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-experimental
        command:
        - ./hack/verify-bazel.sh

  - name: pull-test-infra-verify-config
    branches:
    - master
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-experimental
        command:
        - runner.sh
        args:
        - ./hack/verify-config.sh
        resources:
          requests:
            memory: "2Gi"

  - name: pull-test-infra-verify-config-canary
    branches:
    - master
    path_alias: "k8s.io/test-infra"
    decorate: true
    spec:
      containers:
      - name: test
        command:
        - ./hack/verify-config.sh
        image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-experimental
        env:
        - name: TEST_TMPDIR
          value: /bazel-scratch/.cache/bazel
        resources:
          requests:
            memory: "2Gi"
        volumeMounts:
        - name: bazel-scratch
          mountPath: /bazel-scratch/.cache
      volumes:
      - name: bazel-scratch
        emptyDir: {}

  - name: pull-test-infra-verify-deps
    branches:
    - master
    run_if_changed: '^(go\.mod|go\.sum|WORKSPACE|BUILD\.bazel|hack/verify-deps\.sh|hack/update-deps\.sh|vendor/.*)$'
    decorate: true
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-experimental
        command:
        - runner.sh
        args:
        - ./hack/verify-deps.sh
        resources:
          requests:
            memory: "2Gi"

  - name: pull-test-infra-verify-codegen
    branches:
    - master
    always_run: true
    path_alias: "k8s.io/test-infra"
    decorate: true
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-experimental
        command:
        - ./hack/verify-codegen.sh
        resources:
          requests:
            memory: "2Gi"

  - name: pull-test-infra-verify-gofmt
    branches:
    - master
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-experimental
        command:
        - ./hack/verify-gofmt.sh

  - name: pull-test-infra-verify-labels
    branches:
    - master
    run_if_changed: '^label_sync/labels.yaml'
    decorate: true
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-experimental
        command:
        - runner.sh
        args:
        - ./hack/verify-labels.sh
        resources:
          requests:
            memory: "2Gi"

  - name: pull-test-infra-verify-file-perms
    branches:
    - master
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-experimental
        command:
        - ./hack/verify-file-perms.sh

  - name: pull-test-infra-verify-github-spelling
    branches:
    - master
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190420-93fab49-experimental
        command:
        - ./hack/verify-github-spelling.sh
